// <auto-generated />
using System;
using EmployeePortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeePortal.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260310143210_seeding data")]
    partial class seedingdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeePortal.Data.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0681be5c-f2b2-4eec-b444-c6f1eb4b7f7d"),
                            Email = "jhon@gmail.com",
                            Name = "Jhon",
                            PhoneNumber = "1234567891",
                            Salary = 0m
                        },
                        new
                        {
                            Id = new Guid("b6e6f70c-ad32-48c3-911e-3e55ac5e9b23"),
                            Email = "Sena@gmail.com",
                            Name = "Sena",
                            Salary = 0m
                        },
                        new
                        {
                            Id = new Guid("5d80b3f5-de5b-4cdc-8d43-940239834594"),
                            Email = "JhonWick@gmail.com",
                            Name = "JhonWick",
                            Salary = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
